<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="UTF-8">
    <title>Smi by nevvix</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="stylesheets/normalize.css" media="screen">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" media="screen">
    <link rel="stylesheet" type="text/css" href="stylesheets/github-light.css" media="screen">
    <link rel="stylesheet" type="text/css" href="stylesheets/smi.css" media="screen">
  </head>
  <body>
    <section class="page-header">
      <h1 class="project-name">smi</h1>
      <h2 class="project-tagline">social media icons &amp; links</h2>
      <a href="https://github.com/nevvix/smi" class="btn">View on GitHub</a>
      <a href="https://github.com/nevvix/smi/zipball/master" class="btn">Download .zip</a>
      <a href="https://github.com/nevvix/smi/tarball/master" class="btn">Download .tar.gz</a>
    </section>

    <section class="main-content">

        <h1>Create a social media icon bar<br>without iframes or spying analytics.</h1>

        <p>The goal is for anyone to use this code to create a custom social media icon bar without the iframes used by social media widgets.</p>

        <p>The SVG icon images are produced from Dan Leech's [Simple Icons](https://simpleicons.org/) project.</p>

        <p>We avoid the HTTP requests involved in loading each icon image.</p>

        <p>All the social media links will be added to index.html.</p>

        <h2>Why use it?</h2>

        <ul>
            <li>
                <a href="http://zurb.com/article/883/small-painful-buttons-why-social-media-bu">Those tiny Tweet, Like, +1 buttons you see on websites are actually brutally large elements to load for (mobile) devices."</a>
            </li>
            <li>
                <a href="http://ma.tt/2014/07/canvas-fingerprinting-addthis">Services like AddThis and ShareThis will always spy on and tag your audience when you use their widgets"</a>
            </li>
        </ul>

        <hr>
    
<? foreach (["smi-16", "smi-32", "smi-64"] as $ul_class): ?>
        <ul class="<?= $ul_class ?> cf">
<?     foreach ($json as $title => $attributes): ?>
            <li style="background-color: <?= $attributes->color ?>; border-color: <?= $attributes->color ?>;">
                <a class="<?= $attributes->class ?>" title="<?= $title ?>" href="<?= $attributes->href ?>" rel="nofollow">
                    <?= $attributes->svg ?>
                </a>
            </li>
<?     endforeach ?>
        </ul>
<? endforeach ?>

        <hr>

        <h2>TODO</h2>

        <ul>
            <li>Add all the social media links to index.html.</li>
            <li>Make a social media icon bar example for each icon size in index.html.</li>
        </ul>

      <footer class="site-footer">
        <span class="site-footer-owner"><a href="https://github.com/nevvix/smi">smi</a> is maintained by <a href="https://github.com/nevvix">nevvix</a>.</span>

        <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the <a href="https://github.com/jasonlong/cayman-theme">Cayman theme</a> by <a href="https://twitter.com/jasonlong">Jason Long</a>.</span>
      </footer>

    </section>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-61984930-2', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>

